language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
install:
  - "npm install -g npm"
  - "npm install -g grunt-cli"
  - "npm install"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
sudo: false
